image: node:10.11.0
pipelines:
  default:
    - step:
        script:
          - npm install
  branches:
    master:
      - step:
          script:
            - echo "angular linter"
            - ng lint team-center
    develop:
      - step:
          script:
            - echo "angular linter"
            - ng lint team-center